services:
  - name: finance-backend
    type: web
    runtime: node
    rootDir: backend
    buildCommand: |
      npm install
      npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: true
      - key: PORT
        value: 3000
